config/routes.rb
Notes::Application.routes.draw do

  devise_for :users

  root :to => "notes#index"
  
  match 'notes/monter/:id' => 'notes#monter'
  match 'notes/descendre/:id' => 'notes#descendre'

  resources :categories
  resources :notes

  match ':controller(/:action(/:id(.:format)))'
  

end

app/models/note.rb
class Note < ActiveRecord::Base

  # Associations
  belongs_to :categorie
#  has_and_belongs_to_many :new_categories

  # Validations
  validates_presence_of :titre, :contenu

  # Methodes
  def to_xml(options)
    {
      :categorie => self.categorie.path,
      :titre => self.titre,
      :contenu => self.contenu
    }.to_xml(options)
  end
  
  def monter
    return if self.rang == 1
    rang = self.rang
    if rang.nil?
      derniere = Note.where(:categorie_id => self.categorie_id).order('rang DESC').limit(1).first
      self.rang = derniere.rang.to_i + 1
    else
      precedente = Note.where(:categorie_id => self.categorie_id, :rang => (self.rang - 1)).first
      if precedente.nil?
        self.rang -= 1
      else
        self.rang -= 1
        precedente.rang += 1
        precedente.save
      end 
    end
    
    save
  end
  
  def descendre
    derniere = Note.where(:categorie_id => self.categorie_id).order('rang DESC').limit(1).first
    return if derniere.id == self.id
    rang = self.rang
    if rang.nil?
      self.rang = derniere.rang.to_i + 1
    else
      suivante = Note.where(:categorie_id => self.categorie_id, :rang => (self.rang + 1)).first
      if suivante.nil?
        self.rang += 1
      else
        self.rang += 1
        suivante.rang -= 1
        suivante.save
      end
    end
    
    save
  end
  
end

app/controllers/notes_controller.rb
#encoding: utf-8
class NotesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  # GET /notes
  # GET /notes.xml
  def index
    if params[:search]
      @notes = Note.where("titre LIKE ?", "%#{params[:search]}%").order("created_at DESC").limit(10)
    else
      @notes = Note.order("created_at DESC").limit(10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @note = Note.new(params[:note])

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.xml
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to(edit_note_path(@note), :notice => 'La note a été correctement enregistrée') }
        format.xml  { render :xml => @note, :status => :created, :location => @note }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to(edit_note_path(@note), :notice => 'La note a été correctement mise à jour') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @note = Note.find(params[:id])
    categorie = @note.categorie
    @note.destroy

    respond_to do |format|
      format.html { redirect_to(categorie.nil? ? notes_url : categorie) }
      format.xml  { head :ok }
    end
  end
  
  def monter
    note = Note.find(params[:id])
    note.monter
    redirect_to note.categorie
  end
  
  def descendre
    note = Note.find(params[:id])
    note.descendre
    redirect_to note.categorie
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <dt><%= f.label :titre %></dt>
  <dd><%= f.text_field :titre %></dd>
  <dt><%= f.label :categorie_id %></dt>
  <dd>
    <select id="note_categorie_id" name="note[categorie_id]">
      <%= options_for_select(Categorie.select_map(false), @note.categorie_id) %>
    </select>
  </dd>

  <%= f.text_area :contenu, :cols => 82 %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<% content_for :right do %>
  <div class="column-header">
    <h1>Textile reference</h1>
    <hr/>
  </div>
  
  <div class="column-content">
    <%= render :partial => 'application/textile_reference' %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= note.titre %>" class='note'>  
  
  <h2><%= note.titre %></h2>
  <hr/>
  
  <div class="title_links">
    <%= link_to 'Modifier', edit_note_path(note) %> |
    <%= link_to 'Supprimer', note, :confirm => 'Are you sure?', :method => :delete %> |
    <%= link_to "Monter", :controller => 'notes', :action => 'monter', :id => note.id %> |
    <%= link_to "Descendre", :controller => 'notes', :action => 'descendre', :id => note.id %>
  </div>
      
  <p><%= markdown(note.contenu) %></p>
  
  <p class="no_page"><%= note.rang %></p>
</div>

app/views/notes/edit.html.erb
<div id="content-header" class="column-header">
  <h1>Editing note</h1>
  <hr/>

  <div class="title_links">
    <%= link_to 'Back', @note.categorie %>
  </div>
</div>

<div id="content-content" class="column-content">
  <%= render :partial => 'note', :locals => {:note => @note} %>

  <hr/>

  <%= render 'form' %>
</div>

app/views/notes/index.html.erb
<div id="content-header" class="column-header">
  <h1>Dernières Notes</h1>
  <hr/>
</div>

<!--div id="content-content" class="column-content"-->
  <% @notes.each do |note| %>
    <h3>Categorie: <%= note.categorie.nom unless note.categorie.nil? %></h3>
    
    <%= render :partial => 'note', :locals => {:note => note} %>
  <% end %>

  <% content_for :right do %>
    <%= render :partial => 'categories/toc' %>
  <% end %>
<!--/div-->

app/views/notes/new.html.erb
<h1>Nouvelle note</h1>
<hr/>

<div class="title_links">
  <%= link_to 'Back', notes_path %>
</div>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>