config/routes.rb
Notes::Application.routes.draw do

  devise_for :users

  root :to => "notes#index"
  
  match 'notes/monter/:id' => 'notes#monter'
  match 'notes/descendre/:id' => 'notes#descendre'

  resources :categories
  resources :notes

  match ':controller(/:action(/:id(.:format)))'
  

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]

  # GET /categories
  # GET /categories.xml
  def index
    @categories = Categorie.main

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @categorie = Categorie.find(params[:id])
    @notes = @categorie.notes.where("rang IS NOT NULL").order('rang ASC')
    @notes_without_rang = @categorie.notes.where("rang IS NULL")
    @notes = @notes + @notes_without_rang

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @categorie }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @categorie = Categorie.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @categorie }
    end
  end

  # GET /categories/1/edit
  def edit
    @categorie = Categorie.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @categorie = Categorie.new(params[:categorie])

    respond_to do |format|
      if @categorie.save
        format.html { redirect_to(@categorie, :notice => 'Categorie was successfully created.') }
        format.xml  { render :xml => @categorie, :status => :created, :location => @categorie }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @categorie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @categorie = Categorie.find(params[:id])

    respond_to do |format|
      if @categorie.update_attributes(params[:categorie])
        format.html { redirect_to(@categorie, :notice => 'Categorie was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @categorie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @categorie = Categorie.find(params[:id])
    @categorie.destroy

    respond_to do |format|
      format.html { redirect_to(:root) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_bookmarks.html.erb
<h1>Bookmarks</h1>
<hr/>
        
<% unless @notes.nil? %>
<ul>
  <% @notes.each do |note| %>
    <li><%= link_to note.titre, "##{note.titre}" %></li>
  <% end %>
</ul>
<% end %>

app/views/categories/_categorie.html.erb
<li>
  <%= categorie.nom %> -
  <%= link_to 'Show', categorie %> |
  <%= link_to 'Edit', edit_categorie_path(categorie) %> |
  <%= link_to 'Destroy', categorie, :confirm => 'Are you sure?', :method => :delete %>
  <ul>
    <% categorie.categories.each do |c| %>
      <%= render :partial => "categorie", :locals => { :categorie => c } %>
    <% end %>
  </ul>
</li>

app/views/categories/_form.html.erb
<%= form_for(@categorie) do |f| %>
  <% if @categorie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categorie.errors.count, "error") %> prohibited this categorie from being saved:</h2>

      <ul>
        <% @categorie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <dt><%= f.label :nom %></dt>
  <dd><%= f.text_field :nom %></dd>
  <dt><%= f.label :categorie_id %></dt>
  <dd>
    <select id="categorie_categorie_id" name="categorie[categorie_id]">
      <%= options_for_select(Categorie.select_map, @categorie.categorie_id) %>
    </select>
  </dd>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/categories/_navigation_menu.html.erb
<% if categorie.categories.empty? %>
<li>
<% else %>
<li class="folder expanded">
  <div class="folder-toggle"></div>
<% end %>
  <%= link_to "#{categorie.nom} (#{categorie.notes.count})", categorie %>
  <% unless categorie.categories.empty? %>
    <ul>
      <% categorie.categories.order('nom ASC').each do |c| %>
        <%= render :partial => "categories/navigation_menu", :locals => { :categorie => c } %>
      <% end %>
    </ul>
  <% end %>
</li>

app/views/categories/_navigation_tree.html.erb
<ul>
  <% Categorie.main.each do |categorie| %>
    <%= render :partial => "categories/navigation_menu", :locals => { :categorie => categorie } %>
  <% end %>
</ul>

app/views/categories/_toc.html.erb
<h1>Table of contents</h1>
<hr/>
        
<% unless @notes.nil? %>
<ul>
  <% @notes.each do |note| %>
    <li><%= link_to note.titre, "##{note.titre}" %></li>
  <% end %>
</ul>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing categorie</h1>

<%= render 'form' %>

<%= link_to 'Show', @categorie %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<ul>
  <% @categories.each do |categorie| %>
  <%= render :partial => "categorie", :locals => { :categorie => categorie } %>
  <% end %>
</ul>

<br />

<%= link_to 'New Categorie', new_categorie_path %>

app/views/categories/new.html.erb
<h1>Nouvelle categorie</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1><%= @categorie.nom %></h1>
<hr class="links"/>

<div class="subnav">
  <ul class="nav nav-pills">
    <li><%= link_to 'Nouvelle Note',  new_note_path(:note => {:categorie_id => @categorie.id}) %>
    <li><%= link_to 'Modifier Catégorie', edit_categorie_path(@categorie) %>
    <% if @notes.empty? %>
      <li><%= link_to 'Supprimer Catégorie', @categorie, :confirm => 'Etes-vous sur ?', :method => :delete %>
    <% end %>
  </ul>
</div>

<% @notes.each do |note| %>
  <%= render :partial => 'notes/note', :locals => {:note => note} %>
<% end %>

<% content_for :right do %>
  <%= render :partial => 'toc' %>
<% end %>